USE `TEST3`;

CREATE TABLE `STUDENT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FIRSTNAME` VARCHAR(30) NOT NULL,
  `LASTNAME` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`)
);

INSERT INTO `STUDENT` (`FIRSTNAME`, `LASTNAME`) VALUES ('Dale', 'Cooper');
INSERT INTO `STUDENT` (`FIRSTNAME`, `LASTNAME`) VALUES ('Shelly', 'Johnson');
INSERT INTO `STUDENT` (`FIRSTNAME`, `LASTNAME`) VALUES ('Bobby', 'Briggs');
INSERT INTO `STUDENT` (`FIRSTNAME`, `LASTNAME`) VALUES ('Donna', 'Hayward');
INSERT INTO `STUDENT` (`FIRSTNAME`, `LASTNAME`) VALUES ('Audrey', 'Horne');
INSERT INTO `STUDENT` (`FIRSTNAME`, `LASTNAME`) VALUES ('James', 'Hurley');
INSERT INTO `STUDENT` (`FIRSTNAME`, `LASTNAME`) VALUES ('Lucy', 'Moran');
INSERT INTO `STUDENT` (`FIRSTNAME`, `LASTNAME`) VALUES ('Tommy', 'Hill');
INSERT INTO `STUDENT` (`FIRSTNAME`, `LASTNAME`) VALUES ('Andy', 'Brennan');